#!/usr/bin/env python
# -*- coding: UTF-8 -*-


urlhub = {
	'ClientID':'http://m.ctrip.com/restapi/soa2/10290/createclientid?systemcode=09&createtype=3&head%5Bcid%5D=&head%5Bctok%5D=&head%5Bcver%5D=1.0&head%5Blang%5D=01&head%5Bsid%5D=8888&head%5Bsyscode%5D=09&head%5Bauth%5D=null&head%5Bextension%5D%5B0%5D%5Bname%5D=protocal&head%5Bextension%5D%5B0%5D%5Bvalue%5D=http&contentType=json',
	'Segments':'https://sec-m.ctrip.com/restapi/soa2/11781/Domestic/FlightList/Query?_fxpcqlniredt=',
	'PolicyList':'https://sec-m.ctrip.com/restapi/soa2/11781/Flight/Domestic/CabinList/Query?_fxpcqlniredt=',
	'Refund':'https://sec-m.ctrip.com/restapi/soa2/11781/Domestic/Note/Query?_fxpcqlniredt=',
	'qunaFlightList':'https://m.flight.qunar.com/ncs/api/domestic/flightlist',
	'quanFligthDetail':'https://touch.qunar.com/h5/flight/flightDetail?',
	'quanH5FlightInfo':'https://touch.qunar.com/h5/flight/flightotainfo',
}



requestFlightdata = {"preprdid":"","trptpe":"1","flag":8,"seat":0,"extendinfo":[{"extype":5,"expam":1}],\
"searchitem":None,"sflgno":"",\
"head":{"cid":"09031015111440212896","ctok":"","cver":"1.0","lang":"01","sid":"8888","syscode":"09","auth":None,\
"extension":[{"name":"protocal","value":"http"}]},"contentType":"json"}


requestPolicyListData = {
	"extendinfo": [],
	"flag": "0",
	"prdid": None,
	"polid": "0",
	"triptype": "1",
	"needrtd": True,
	"ver": 0,
	"head": {
		"cid": None,
		"ctok": "",
		"cver": "1.0",
		"lang": "01",
		"sid": "8888",
		"syscode": "09",
		"auth": None,
		"extension": [{
			"name": "protocal",
			"value": "http"
		}]
	},
	"contentType": "json"
}

requestRefundChangeData = {
							"flag": 15,
							"prpid": None,
							"head": {
								"cid": None,
								"ctok": "",
								"cver": "1.0",
								"lang": "01",
								"sid": "8888",
								"syscode": "09",
								"auth": None,
								"extension": [{
									"name": "protocal",
									"value": "http"
								}]
							},
							"contentType": "json"
						}


header = {"User-Agent":"Mozilla/5.0 (Linux; Android 6.0; HUAWEI Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36"}



cityDic = {
	"阿尔山":"YIE",
	"阿克苏":"AKU",
	"额济纳旗":"9AL",
	"阿拉善右旗":"RHT",
	"阿拉善左旗":"AXF",
	"阿勒泰":"AAT",
	"阿里":"NGQ",
	"安康":"AKA",
	"安庆":"AQG",
	"鞍山":"AOG",
	"安顺":"AVA",
	"百色":"AEB",
	"保山":"BSD",
	"包头":"BAV",
	"巴彦淖尔":"RLK",
	"北海":"BHY",
	"北京":"BJS",
	"毕节":"BFJ",
	"博乐":"BPL",
	"长白山":"NBS",
	"长春":"CGQ",
	"常德":"CGD",
	"昌都":"BPX",
	"长海":"CNI",
	"长沙":"CSX",
	"长治":"CIH",
	"常州":"CZX",
	"朝阳":"CHG",
	"成都":"CTU",
	"赤峰":"CIF",
	"重庆":"CKG",
	"大理":"DLU",
	"大连":"DLC",
	"丹东":"DDG",
	"稻城":"DCY",
	"大庆":"DQA",
	"大同":"DAT",
	"达州":"DAX",
	"德令哈":"HXD",
	"香格里拉":"DIG",
	"东营":"DOY",
	"敦煌":"DNH",
	"鄂尔多斯":"DSN",
	"峨眉山":"9EM",
	"恩施":"ENH",
	"二连浩特":"ERL",
	"佛山":"FUO",
	"阜阳":"FUG",
	"抚远":"FYJ",
	"富蕴":"FYN",
	"福州":"FOC",
	"赣州":"KOW",
	"格尔木":"GOQ",
	"广汉":"GHN",
	"广元":"GYS",
	"广州":"CAN",
	"桂林":"KWL",
	"贵阳":"KWE",
	"固原":"GYU",
	"哈尔滨":"HRB",
	"海口":"HAK",
	"海拉尔":"HLD",
	"哈密":"HMI",
	"邯郸":"HDG",
	"杭州":"HGH",
	"汉中":"HZG",
	"河池":"8HC",
	"合肥":"HFE",
	"黑河":"HEK",
	"衡阳":"HNY",
	"和田":"HTN",
	"淮安":"HIA",
	"黄山":"TXN",
	"黄石":"9HS",
	"呼和浩特":"HET",
	"惠州":"HUZ",
	"加格达奇":"JGD",
	"佳木斯":"JMU",
	"江门":"9JM",
	"嘉兴":"9JX",
	"嘉峪关":"JGN",
	"揭阳":"SWA",
	"济南":"TNA",
	"金昌":"JIC",
	"景德镇":"JDZ",
	"井冈山":"JGS",
	"沙市":"SHS",
	"济宁":"JNG",
	"泉州":"JJN",
	"锦州":"JNZ",
	"九江":"JIU",
	"嘉兴":"JZH",
	"鸡西":"JXA",
	"凯里":"KJH",
	"喀纳斯":"KJI",
	"康定":"KGT",
	"喀什":"KHG",
	"克拉玛依":"KRY",
	"库车":"KCA",
	"库尔勒":"KRL",
	"昆明":"KMG",
	"昆山":"9KS",
	"兰州":"LHW",
	"拉萨":"LXA",
	"乐山":"9LS",
	"梁平":"LIA",
	"连云港":"LYG",
	"荔波":"LLB",
	"丽江":"LJG",
	"临沧":"LNJ",
	"临汾":"LFQ",
	"林西":"LXI",
	"临沂":"LYI",
	"林芝":"LZY",
	"黎平":"HZH",
	"六盘水":"LPF",
	"柳州":"LZH",
	"连城":"LCX",
	"洛阳":"LYA",
	"泸州":"LZO",
	"吕梁":"LLV",
	"芒市":"LUM",
	"满洲里":"NZH",
	"眉山":"9MS",
	"梅县":"MXZ",
	"绵阳":"MIG",
	"漠河":"OHE",
	"牡丹江":"MDG",
	"那拉提":"NLT",
	"南昌":"KHN",
	"南充":"NAO",
	"南京":"NKG",
	"南宁":"NNG",
	"南平":"9NP",
	"南通":"NTG",
	"南阳":"NNY",
	"宁波":"NGB",
	"攀枝花":"PZI",
	"普洱":"SYM",
	"黔江":"JIQ",
	"且末":"IQM",
	"青岛":"TAO",
	"庆阳":"IQN",
	"秦皇岛":"SHP",
	"齐齐哈尔":"NDG",
	"泉州":"QUZ",
	"衢州":"JUZ",
	"日喀则":"RKZ",
	"日照":"RIZ",
	"三明":"9SM",
	"三亚":"SYX",
	"上海":"SHA",
	"鄯善":"SXJ",
	"韶关":"HSC",
	"神农架":"HPG",
	"沈阳":"SHE",
	"深圳":"SZX",
	"石家庄":"SJW",
	"十堰":"WDS",
	"四平":"9SP",
	"苏州":"SZV",
	"塔城":"TCG",
	"太原":"TYN",
	"台州":"HYN",
	"唐山":"TVS",
	"腾冲":"TCZ",
	"天津":"TSN",
	"天水":"THQ",
	"通化":"TNH",
	"通辽":"TGO",
	"铜仁":"TEN",
	"吐鲁番":"TLQ",
	"万州":"WXN",
	"潍坊":"WEF",
	"威海":"WEH",
	"文山":"WNH",
	"温州":"WNZ",
	"乌海":"WUA",
	"武汉":"WUH",
	"乌兰察布":"UCB",
	"乌兰浩特":"HLH",
	"乌鲁木齐":"URC",
	"无锡":"WUX",
	"武夷山":"WUS",
	"梧州":"WUZ",
	"夏河":"GXH",
	"厦门":"XMN",
	"西安":"XIY",
	"襄阳(中国)":"XFN",
	"西昌":"XIC",
	"锡林浩特":"XIL",
	"兴城":"XCC",
	"邢台":"XIN",
	"兴义":"ACX",
	"西宁":"XNN",
	"信阳":"8XY",
	"忻州":"XZS",
	"西双版纳":"JHG",
	"徐州":"XUZ",
	"延安":"ENY",
	"盐城":"YNZ",
	"扬州":"YTY",
	"延吉":"YNJ",
	"烟台":"YNT",
	"宜宾":"YBP",
	"宜昌":"YIH",
	"伊春":"LDS",
	"宜春":"YIC",
	"银川":"INC",
	"营口":"YKH",
	"伊宁":"YIN",
	"义乌":"YIW",
	"永州":"LLF",
	"岳阳":"9UY",
	"榆林":"UYN",
	"运城":"YCU",
	"玉树":"YUS",
	"张家界":"DYG",
	"张家口":"ZQZ",
	"张掖":"YZY",
	"湛江":"ZHA",
	"昭通":"ZAT",
	"郑州":"CGO",
	"镇江":"9ZJ",
	"中山":"9ZS",
	"中卫":"ZHY",
	"舟山":"HSN",
	"珠海":"ZUH",
	"株洲":"9ZO",
	"遵义":"ZYI",
}

#inds = {"sd":"北京"}

#print inds["sd"]
#print cityDic[inds["sd"]]
'''
cityDic = {
	"AKU":"阿克苏",
	"AQG":"安庆",
	"AAT":"阿勒泰",
	"AKA":"安康",
	"AOG":"鞍山",
	"AHJ":"阿坝",

	"AVA":"安顺",
	"YIE":"阿尔山",
	"NGQ":"阿里",
	"RHT":"阿拉善右旗",
	"AXF":"阿拉善左旗",
	"MFM":"澳门",
	"PEK":"北京",
	"BAV":"包头",
	"BHY":"北海",
	"BSD":"保山",
	"AEB":"百色",
	"RLK":"巴彦淖尔",
	"BFJ":"毕节",
	"BAR":"博鳌",
	"BPL":"博乐",
	"NBD":"保定",
	"DBC":"白城",
	"CTU":"成都",
	"CKG":"重庆",
	"CSX":"长沙",
	"CGQ":"长春",
	"CZX":"常州",
	"CGD":"常德",
	"CIH":"长治",
	"CIF":"赤峰",
	"CHG":"朝阳",
	"NBS":"长白山",
	"JUH":"池州",
	"BPX":"昌都",
	"HZN":"沧州",
	"CNI":"长海",
	"LQP":"郴州",
	"CWJ":"沧源",
	"DLC":"大连",
	"DDG":"丹东",
	"DLU":"大理",
	"DAT":"大同",
	"DOY":"东营",
	"DNH":"敦煌",
	"DAX":"达州",
	"DQA":"沧州",
	"HZN":"大庆",
	"DCY":"稻城",
	"DYN":"丹阳",
	"HXD":"德令哈",
	"ENH":"恩施",
	"DSN":"鄂尔多斯",
	"ERL":"二连浩特",
	"EJN":"额济纳旗",
	"EMH":"峨眉山",
	"FOC":"福州",
	"FUG":"阜阳",
	"FYN":"富蕴",
	"FUO":"佛山",
	"FYJ":"抚远",
	"CAN":"广州",
	"KWE":"贵阳",
	"KWL":"桂林",
	"KOW":"赣州",
	"GYS":"广元",
	"GOQ":"格尔木",
	"GHN":"广汉",
	"GYU":"固原",
	"GMQ":"果洛",
	"GXH":"夏河",
	"KHH":"高雄",
	"LHK":"光化",
	"HGH":"杭州",
	"HAK":"海口",
	"HRB":"哈尔滨",
	"HFE":"合肥",
	"HET":"呼和浩特",
	"HLD":"海拉尔",
	"HDG":"邯郸",
	"TXN":"和田",
	"HUZ":"惠州",
	"HZG":"汉中",
	"HNY":"衡阳",
	"HEK":"黑河",
	"HMI":"哈密",
	"HIA":"淮安",
	"HSQ":"黄石",
	"HCJ":"河池",
	"HCN":"恒春",
	"HUN":"花莲",
	"HYN":"台州",
	"HTT":"花土沟",
	"HUO":"霍林郭勒",
	"TNA":"济南",
	"SWA":"揭阳",
	"JMU":"佳木斯",
	"JHG":"西双版纳",
	"JNZ":"锦州",
	"JDZ":"景德镇",
	"JIU":"九江",
	"JNG":"济宁",
	"JGS":"井冈山",
	"JGN":"嘉峪关",
	"JZH":"九寨沟",
	"JGD":"加格达奇",
	"JXA":"鸡西",
	"JXS":"嘉兴",
	"JIC":"金昌",
	"JBD":"江门",
	"KNH":"金门",
	"CYI":"嘉义",
	"JJN":"泉州",
	"JAY":"江油",
	"JLE":"将乐",
	"JIG":"建宁",
	"JIS":"江山",
	"KMG":"昆明",
	"KHG":"喀什",
	"KRL":"库尔勒",
	"KCA":"库车",
	"KRY":"克拉玛依",
	"KJI":"喀纳斯",
	"KGT":"康定",
	"KVN":"昆山",
	"KJH":"凯里",
	"LHW":"兰州",
	"LJG":"丽江",
	"LXA":"拉萨",
	"LZH":"柳州",
	"LYA":"洛阳",
	"LYG":"连云港",
	"LYI":"临沂",
	"LZO":"泸州",,
	"LNJ":"临沧",
	"LCX":"连城",
	"HZH":"黎平",
	"LLB":"荔波",
	"LIA":"梁平",
	"LQS":"陵水",
	"LSG":"乐山",
	#"":"辽阳"
	"LFQ":"临汾",
	"LZY":"林芝",
	"LLV":"吕梁",
	"LPF":"六盘水",
	"GNI":"绿岛",
	"KYD":"兰屿",
	"LXI":"林西",
	"MDG":"牡丹江",

}
'''